# Generated by Django 4.2.2 on 2023-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_des', models.TextField()),
                ('c_image', models.ImageField(max_length=500, upload_to='courses')),
                ('c_review', models.IntegerField(default=0)),
                ('actual_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('craeted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
